workflows:
  domain-tests:
    name: Domain unit tests
    environment:
      xcode: latest
    scripts:
      - name: Run SwiftLint
        script: |
          brew install swiftlint
          swiftlint lint --strict
      - name: Run tests with coverage
        script: |
          xcodebuild test \
          -scheme Domain \
          -destination 'platform=iOS Simulator,name=iPhone 17' \
          -enableCodeCoverage YES \
          -skipPackagePluginValidation
      - name: Upload coverage to Codecov
        script: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -t ffac83e8-c62b-480c-8e0d-9ed121434465
    publishing:
      email:
        recipients:
          - jonrysimbolon19@gmail.com
